<a href="https://colab.research.google.com/github/bartosz-bicki/data-science-bootcamp/blob/master/01_wprowadzenie/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hello')

hello


In [2]:
import numpy as np 
np.__version__

'1.18.5'

In [3]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
x.dtype

dtype('int64')

In [10]:
x = np.array([1.3, 1.6, 2.9])
print(x)

[1.3 1.6 2.9]


In [13]:
x = np.array([[1, 2], [5, 3]])


In [16]:
x = np.array(
    [[[4,3,2],
      [3,1,6]],
      [[4,1,3],
      [5,7,2]]]
)
x

array([[[4, 3, 2],
        [3, 1, 6]],

       [[4, 1, 3],
        [5, 7, 2]]])

In [17]:
x.ndim

3

In [18]:
x.shape

(2, 2, 3)

Typy danych 

In [21]:
a = np.array([24,120,230], dtype=np.uint8)
a.dtype

dtype('uint8')

Tworzenie tablic 

In [22]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full(shape=(3, 3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [26]:
np.arange(start=10, stop=100, step = 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [27]:
np.linspace(start=1, stop=5, num=11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [37]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
a.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Podstawowe operacje na tablicach 

In [39]:
a = np.array([3,2,1])
b = np.array([6,2,4])
a + b 

array([9, 4, 5])

In [40]:
a*b

array([18,  4,  4])

In [41]:
X = np.array([[1,3], [2,5]]) 
Y = np.array([[2,3], [5, 7]])
np.dot(X, Y)

array([[17, 24],
       [29, 41]])

Generowanie liczb pseudolosowych 

In [ ]:
np.random.seed(0)

In [42]:
np.random.randn(5, 3)

array([[ 1.18860486, -1.11372144, -0.68892325],
       [ 2.87445451,  1.48164856,  0.67960964],
       [ 1.67496509,  0.79503516,  0.41747149],
       [ 0.64165357, -0.39611146,  0.92292911],
       [ 0.46686334,  1.61007673, -0.30880581]])

Podstawowe funkcje 

In [43]:
a = np.random.rand(5)
a

array([0.72649476, 0.19598601, 0.44668816, 0.5829259 , 0.17662051])

In [45]:
a[np.argmax(a)]

0.7264947618910623

In [46]:
np.argsort(a)

array([4, 1, 2, 3, 0])

Indeksowanie i wycinanie

In [49]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
a[:,0]

array([ 0,  5, 10, 15])

In [52]:
for row in a:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


zmiana rozmiaru 

In [53]:
a.shape

(4, 5)

In [54]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [55]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [59]:
a = np.arange(start=-10, stop=10,step=0.5)
a = a.reshape(10,-1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [62]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])